services:
  backend:
    build: ./backend
    ports:
      - "8001:8000"
    environment:
      DB_PATH: /backend/data/db1.db
    volumes:
      - data:/backend/data
  frontend:
    build: ./frontend
    ports:
      - "8000:80"
    depends_on:
      - backend

volumes:
  data:
